name: CI/CD

on:
  pull_request:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      refToBuild:
        description: "Branch, tag or commit SHA1 to build"
        required: true
        type: string

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cicd:
    name: CI/CD
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-4-dev \
            libadwaita-1-dev \
            libglib2.0-dev \
            libwebkitgtk-6.0-dev \
            blueprint-compiler
            
      - uses: actions/checkout@v4.2.2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --release -v
        env:
          RUST_BACKTRACE: 1

      - name: Rename binary
        run: |
          ls -la ./target/release/
          mv ./target/release/sphereview ./sphereview-linux-${{ endsWith(matrix.os, 'arm') && 'arm64' || 'x64' }}
          ls -la

      # For security reasons, github doesn't allow setting envvars using expressions
      # directly. Therefore, we need an extra step:
      - name: Set current date as env variable
        shell: bash -l {0}
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Internal release
        uses: softprops/action-gh-release@v2
        if: github.repository_owner == 'dynobo'
        with:
          name: Internal
          body: "Only for internal tests. Should not be published. [${{ env.NOW }}]"
          draft: true
          prerelease: true
          tag_name: internal
          files: |
            sphereview-linux-x64
            sphereview-linux-arm64
          fail_on_unmatched_files: false

      - name: Release
        uses: softprops/action-gh-release@v2
        if: |
          startsWith(github.ref, 'refs/tags/v')
          && github.repository_owner == 'dynobo'
        with:
          body: "See [changelog](https://github.com/dynobo/sphereview/blob/main/CHANGELOG) for details."
          draft: true
          prerelease: false